version: "3.5"

networks:
  celery-vs-grpc-local:
    external: true

services:

  worker-d:
    build:
      context: .
      dockerfile: .docker/Dockerfile
    # platform: linux/amd64
    image: and-ratajski/celery-vs-grpc-worker-d:latest
    container_name: celery-vs-grpc-worker-d
    restart: always
    env_file:
      - ../../db.env.local  # DB setup
      - ../celery.env.local
      - ./.env.local
    volumes:
     - ./app:/app
    networks:
      - celery-vs-grpc-local
    command: >
       --hostname=worker-d@%h
       --pool=solo
       --concurrency=1
       --loglevel=INFO
