version: "3.5"

volumes:
  celery-vs-grpc-data: {}

networks:
  celery-vs-grpc-local:
    external: true

services:
  postgres:
    build:
      context: .docker
      dockerfile: Dockerfile
    image: and-ratajski/celery-vs-grpc-postgres:latest
    restart: always
    container_name: celery-vs-grpc-postgres
    volumes:
      - "celery-vs-grpc-data:/var/lib/postgresql/data"
    networks:
      - celery-vs-grpc-local
    ports:
      - "5432:5432"
    env_file:
      - ../db.env.local
