version: "3.5"

networks:
  celery-vs-grpc-local:
    external: true

services:

  worker-a:
    build:
      context: .docker
      dockerfile: Dockerfile
    # platform: linux/amd64
    image: and-ratajski/celery-vs-grpc-worker-a:latest
    container_name: celery-vs-grpc-worker-a
    restart: always
    env_file:
      - ../celery.env.local
      - ./.env.local
    volumes:
     - ./app:/app
    networks:
      - celery-vs-grpc-local
    command: >
       --exclude-queues=${CELERY_FOLLOWUP_QUEUE}
       --hostname=worker-a@%h
       --pool=solo
       --concurrency=1
       --loglevel=INFO
