version: "3.5"

networks:
  celery-vs-grpc-local:
    external: true

services:

  service-b:
    build:
      context: ..
      dockerfile: ServiceB/.docker/Dockerfile
    # platform: linux/amd64
    image: and-ratajski/celery-vs-grpc-service-b:latest
    container_name: celery-vs-grpc-service-b
    restart: always
    env_file:
      - ./.env.local
    volumes:
     - ./app:/app
    networks:
      - celery-vs-grpc-local
#    ports:
#      - "50051:50051"